ALTER TABLE AD_TCSPRO
 DROP PRIMARY KEY CASCADE;

DROP TABLE TESTE.AD_TCSPRO CASCADE CONSTRAINTS;

CREATE TABLE TESTE.AD_TCSPRO
(
  NUMOS           NUMBER(10)                    NOT NULL,
  SEQPRO          NUMBER(10)                    NOT NULL,
  CODPROD         NUMBER(10),
  QTDPREV         FLOAT(126)                    NOT NULL,
  QTDENTREGUE     FLOAT(126),
  QTDDEVOLVIDA    FLOAT(126),
  QTDAPLICADA     FLOAT(126),
  CODOCOROS       NUMBER(5),
  VLRUNIT         FLOAT(126),
  VLRTOTAL        FLOAT(126),
  VLRDESC         FLOAT(126),
  NUTIPATD        NUMBER(10),
  ORIGEM          VARCHAR2(10 BYTE),
  CODUSUINC       NUMBER(5),
  DHINC           DATE,
  CODUSUALTER     NUMBER(5),
  DHALTER         DATE,
  NUMOTIVO        NUMBER(10),
  STATUSOS        VARCHAR2(100 BYTE),
  VLRUNITAPL      FLOAT(126),
  VLRTOTAPL       FLOAT(126),
  VLRLIQAPL       FLOAT(126),
  QTDSOLICITADO   FLOAT(126),
  FATSERV         VARCHAR2(10 BYTE),
  CODUSUREGDESC   NUMBER(5),
  CODUSUAPRDESC   NUMBER(5),
  DHREGDESC       DATE,
  NUMNOTACPA      NUMBER(10),
  VLRCPA          FLOAT(126),
  OBSCPA          VARCHAR2(4000 BYTE),
  RAZAOSOCIALCPA  VARCHAR2(100 BYTE),
  DTCPA           DATE,
  DHALTATD        DATE,
  CODCENCUS       NUMBER(10),
  AD_EXCEPCIONAL  VARCHAR2(10 BYTE)
)
TABLESPACE SANKHYA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;


CREATE INDEX TESTE.AD_TCSPRO_IDX_FK_CODOCOROS ON TESTE.AD_TCSPRO
(CODOCOROS)
LOGGING
TABLESPACE SANKHYA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

CREATE INDEX TESTE.AD_TCSPRO_IDX_FK_CODPROD ON TESTE.AD_TCSPRO
(CODPROD)
LOGGING
TABLESPACE SANKHYA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

CREATE INDEX TESTE.AD_TCSPRO_IDX_FK_CODUSUALTE ON TESTE.AD_TCSPRO
(CODUSUALTER)
LOGGING
TABLESPACE SANKHYA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

CREATE INDEX TESTE.AD_TCSPRO_IDX_FK_CODUSUAPRD ON TESTE.AD_TCSPRO
(CODUSUAPRDESC)
LOGGING
TABLESPACE SANKHYA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

CREATE INDEX TESTE.AD_TCSPRO_IDX_FK_CODUSUINC ON TESTE.AD_TCSPRO
(CODUSUINC)
LOGGING
TABLESPACE SANKHYA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

CREATE INDEX TESTE.AD_TCSPRO_IDX_FK_CODUSUREGD ON TESTE.AD_TCSPRO
(CODUSUREGDESC)
LOGGING
TABLESPACE SANKHYA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

CREATE INDEX TESTE.AD_TCSPRO_IDX_FK_NUMOTIVO ON TESTE.AD_TCSPRO
(NUMOTIVO)
LOGGING
TABLESPACE SANKHYA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

CREATE INDEX TESTE.AD_TCSPRO_IDX_FK_NUTIPATD ON TESTE.AD_TCSPRO
(NUTIPATD)
LOGGING
TABLESPACE SANKHYA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

CREATE UNIQUE INDEX TESTE.AD_UK_TCSPRO_CODPROD ON TESTE.AD_TCSPRO
(NUMOS, CODPROD)
LOGGING
TABLESPACE SANKHYA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

CREATE UNIQUE INDEX TESTE.PK_AD_TCSPRO ON TESTE.AD_TCSPRO
(NUMOS, SEQPRO)
LOGGING
TABLESPACE SANKHYA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

ALTER TABLE TESTE.AD_TCSPRO ADD (
  CONSTRAINT PK_AD_TCSPRO
  PRIMARY KEY
  (NUMOS, SEQPRO)
  USING INDEX TESTE.PK_AD_TCSPRO
  ENABLE VALIDATE,
  CONSTRAINT AD_UK_TCSPRO_CODPROD
  UNIQUE (NUMOS, CODPROD)
  USING INDEX TESTE.AD_UK_TCSPRO_CODPROD
  ENABLE VALIDATE);

ALTER TABLE TESTE.AD_TCSPRO ADD (
  CONSTRAINT AD_FK_1C69716D26B93065EDFD7 
  FOREIGN KEY (CODOCOROS) 
  REFERENCES TESTE.TCSOOS (CODOCOROS)
  ENABLE VALIDATE,
  CONSTRAINT AD_FK_32FD316D3B2B94393BDB5 
  FOREIGN KEY (CODUSUALTER) 
  REFERENCES TESTE.TSIUSU (CODUSU)
  ENABLE VALIDATE,
  CONSTRAINT AD_FK_3B24116D26B129E427AAD 
  FOREIGN KEY (CODPROD) 
  REFERENCES TESTE.TGFPRO (CODPROD)
  ENABLE NOVALIDATE,
  CONSTRAINT AD_FK_5695F1744A951CD16D038 
  FOREIGN KEY (CODCENCUS) 
  REFERENCES TESTE.TSICUS (CODCENCUS)
  ENABLE VALIDATE,
  CONSTRAINT AD_FK_66C1A16D3B2AC6BCF21B4 
  FOREIGN KEY (CODUSUINC) 
  REFERENCES TESTE.TSIUSU (CODUSU)
  ENABLE VALIDATE,
  CONSTRAINT AD_FK_98B5416D26B093D10BE1E 
  FOREIGN KEY (NUMOS) 
  REFERENCES TESTE.AD_TCSOSE (NUMOS)
  ENABLE VALIDATE,
  CONSTRAINT AD_FK_9E8F117208D4F142DD4DA 
  FOREIGN KEY (CODUSUREGDESC) 
  REFERENCES TESTE.TSIUSU (CODUSU)
  ENABLE VALIDATE,
  CONSTRAINT AD_FK_A703216D26BD25B5B9179 
  FOREIGN KEY (NUTIPATD) 
  REFERENCES TESTE.AD_TIPATD (NUTIPATD)
  ENABLE VALIDATE,
  CONSTRAINT AD_FK_E73D317208D5C34CE4044 
  FOREIGN KEY (CODUSUAPRDESC) 
  REFERENCES TESTE.TSIUSU (CODUSU)
  ENABLE VALIDATE,
  CONSTRAINT AD_FK_FBCAF16D73F07976A68ED 
  FOREIGN KEY (NUMOTIVO) 
  REFERENCES TESTE.TCSMTE (NUMOTIVO)
  ENABLE VALIDATE);
