SELECT AD_TCSOSE.AD_TIPATE AS AD_TIPATE
      ,AD_TCSOSE.CEP AS CEP
      ,AD_TCSOSE.CODCENCUS AS CODCENCUS
      ,AD_TCSOSE.CODCONTATO AS CODCONTATO
      ,AD_TCSOSE.CODEMP AS CODEMP
      ,AD_TCSOSE.CODERRO AS CODERRO
      ,AD_TCSOSE.CODOCOROS AS CODOCOROS
      ,AD_TCSOSE.CODPARC AS CODPARC
      ,AD_TCSOSE.CODPARCMAQ AS CODPARCMAQ
      ,AD_TCSOSE.CODPROD AS CODPROD
      ,AD_TCSOSE.CODTIPVENDAPRO AS CODTIPVENDAPRO
      ,AD_TCSOSE.CODTIPVENDASERV AS CODTIPVENDASERV
      ,AD_TCSOSE.CODUSUALTER AS CODUSUALTER
      ,AD_TCSOSE.CODUSUFECH AS CODUSUFECH
      ,AD_TCSOSE.CODUSUINC AS CODUSUINC
      ,AD_TCSOSE.CODUSUMEC AS CODUSUMEC
      ,AD_TCSOSE.CODUSURESP AS CODUSURESP
      ,AD_TCSOSE.COMPLEMENTO AS COMPLEMENTO
      ,AD_TCSOSE.DHCHAMADA AS DHCHAMADA
      ,AD_TCSOSE.DTALTER AS DTALTER
      ,AD_TCSOSE.DTAVARIA AS DTAVARIA
      ,AD_TCSOSE.DTFECHAMENTO AS DTFECHAMENTO
      ,AD_TCSOSE.DTINICIOUSOREG AS DTINICIOUSOREG
      ,AD_TCSOSE.DTPREVISTA AS DTPREVISTA
      ,AD_TCSOSE.LOCALEXECUCAO AS LOCALEXECUCAO
      ,AD_TCSOSE.NOMEBAI AS NOMEBAI
      ,AD_TCSOSE.NOMECID AS NOMECID
      ,AD_TCSOSE.NOMEEND AS NOMEEND
      ,AD_TCSOSE.NROCLAIN AS NROCLAIN
      ,AD_TCSOSE.NROLIQ AS NROLIQ
      ,AD_TCSOSE.NROREQUISICAO AS NROREQUISICAO
      ,AD_TCSOSE.NUCHASSI AS NUCHASSI
      ,AD_TCSOSE.NUEND AS NUEND
      ,AD_TCSOSE.NUMEND AS NUMEND
      ,AD_TCSOSE.NUMOS AS NUMOS
      ,AD_TCSOSE.NUNOTA AS NUNOTA
      ,AD_TCSOSE.NUPARMAQ AS NUPARMAQ
      ,AD_TCSOSE.NUPMP AS NUPMP
      ,AD_TCSOSE.NUTIPATD AS NUTIPATD
      ,AD_TCSOSE.OBSCLIENTE AS OBSCLIENTE
      ,AD_TCSOSE.OBSFAT AS OBSFAT
      ,AD_TCSOSE.SEQUENCIA AS SEQUENCI
      ,AD_TCSOSE.SITUACAO AS SITUACAO
      ,AD_TCSOSE.STATUSOS AS STATUSOS
      ,AD_TCSOSE.TIPOGAR AS TIPOGAR
      ,(SELECT MAX(NVL(TPP.AD_AGLEADER,'N'))
                FROM TGFPAR PAR
                LEFT JOIN TGFTPP TPP ON (TPP.CODTIPPARC = PAR.AD_PERFILCLI)
                WHERE ((PAR.CODPARC = AD_TCSOSE.CODPARC) OR (PAR.CODPARC IN (SELECT PAR2.CODPARCMATRIZ FROM TGFPAR PAR2 WHERE PAR2.CODPARC =  AD_TCSOSE.CODPARC)))) AS AGLEADER

      ,(SELECT CGC_CPF
                FROM TGFPAR PAR
                WHERE PAR.CODPARC = AD_TCSOSE.CODPARC) AS CNPJ

      ,(SELECT PAR.CODPARCMATRIZ
                FROM TGFPAR PAR
                WHERE PAR.CODPARC = AD_TCSOSE.CODPARC) AS CODPARCMATRIZ

      ,(SELECT CODUSUINC FROM AD_VGFACO
        WHERE NUMOS = AD_TCSOSE.NUMOS
                AND SEQACO IN (SELECT MAX(SEQACO)FROM AD_VGFACO
                WHERE NUMOS = AD_TCSOSE.NUMOS
                AND NVL(DTCONTATO,SYSDATE) IN (SELECT NVL(MAX(DTCONTATO),SYSDATE) FROM AD_VGFACO WHERE NUMOS = AD_TCSOSE.NUMOS))) AS CODUSUOCOR

      ,(SELECT TRIM(PAR.NOMEPARC) ||' - ' || TRIM(PRO.DESCRPROD)
                FROM AD_TCSOSE OSE,TGFPAR PAR,TGFPRO PRO
                WHERE OSE.NUMOS = AD_TCSOSE.NUMOS
                AND OSE.CODPARC =  PAR.CODPARC
                AND OSE.CODPROD =  PRO.CODPROD) AS DESCRICAO

      ,(SELECT MAX(HR.DTHORIMETRO)
                FROM AD_MAQHOR HR
                WHERE HR.CODPARC =  AD_TCSOSE.CODPARCMAQ
                AND HR.NUPARMAQ = AD_TCSOSE.NUPARMAQ
                AND HR.NUMOS = AD_TCSOSE.NUMOS) AS DTHORIMETRO

      ,(SELECT MAX(HR.DTHORIMETRO)
                FROM AD_MAQHOR HR
                WHERE (CODPARC,NUPARMAQ) IN (SELECT OSE.CODPARCMAQ,OSE.NUPARMAQ FROM AD_TCSOSE OSE WHERE OSE.NUMOS = AD_TCSOSE.NUMOS)
                AND HR.DTHORIMETRO <= NVL((SELECT HR2.DTHORIMETRO FROM AD_MAQHOR HR2 WHERE HR2.CODPARC =  HR.CODPARC AND HR2.NUPARMAQ =  HR.NUPARMAQ AND HR2.NUMOS = AD_TCSOSE.NUMOS),TRUNC(SYSDATE))) AS DTHORIMETROANT

      ,(SELECT PAR.DTINICIOUSO FROM AD_PARMAQ PAR
                WHERE (PAR.CODPARC,PAR.NUPARMAQ) IN (SELECT CH.CODPARC,CH.NUPARMAQ FROM AD_CHASSI CH WHERE CH.NUCHASSI = AD_TCSOSE.NUCHASSI)) AS DTINICIOUSO

      ,(SELECT NVL(GARANTIA,'N')
                FROM AD_TIPATD
                WHERE NUTIPATD = AD_TCSOSE.NUTIPATD) AS GARANTIA

      ,(SELECT NVL(HR.HORIMETRO,0)
                FROM AD_MAQHOR HR
                WHERE HR.CODPARC = AD_TCSOSE.CODPARCMAQ
                AND HR.NUPARMAQ =  AD_TCSOSE.NUPARMAQ
                AND HR.NUMOS = AD_TCSOSE.NUMOS) AS HORIMETRO

      ,(SELECT MAX(HR.HORIMETRO)
                FROM AD_MAQHOR HR
                WHERE (CODPARC,NUPARMAQ) IN (SELECT OSE.CODPARCMAQ,OSE.NUPARMAQ
                                               FROM AD_TCSOSE OSE WHERE OSE.NUMOS = AD_TCSOSE.NUMOS)
                AND HR.DTHORIMETRO <= NVL((SELECT MAX(HR2.DTHORIMETRO)
                                             FROM AD_MAQHOR HR2 WHERE HR2.CODPARC =  HR.CODPARC
                                                                 AND HR2.NUPARMAQ =  HR.NUPARMAQ
                                                                 AND HR2.NUMOS =AD_TCSOSE.NUMOS),TRUNC(SYSDATE))) AS HORIMETROANT

      ,(SELECT MAQ.NROCHASSI
                FROM AD_PARMAQ MAQ
                WHERE MAQ.CODPARC =  AD_TCSOSE.CODPARCMAQ
                AND MAQ.NUPARMAQ =  AD_TCSOSE.NUPARMAQ) AS NROCHASSI

      ,(SELECT MAQ.NROPATRIMONIO
                FROM AD_PARMAQ MAQ
                WHERE MAQ.CODPARC =  AD_TCSOSE.CODPARCMAQ
                AND MAQ.NUPARMAQ =  AD_TCSOSE.NUPARMAQ) AS NROPATRIMONIO

      ,(SELECT NUOCO FROM AD_VGFACO
                WHERE NUMOS = AD_TCSOSE.NUMOS
                AND SEQACO IN (SELECT MAX(SEQACO)FROM AD_VGFACO
                WHERE NUMOS = AD_TCSOSE.NUMOS
                AND NVL(DTCONTATO,SYSDATE) IN (SELECT NVL(MAX(DTCONTATO),SYSDATE) FROM AD_VGFACO WHERE NUMOS = AD_TCSOSE.NUMOS))) AS NUOCO

      ,(SELECT DESCRICAO FROM AD_VGFACO
                WHERE NUMOS = AD_TCSOSE.NUMOS
                AND SEQACO IN (SELECT MAX(SEQACO)FROM AD_VGFACO
                WHERE NUMOS = AD_TCSOSE.NUMOS
                AND NVL(DTCONTATO,SYSDATE) IN (SELECT NVL(MAX(DTCONTATO),SYSDATE) FROM AD_VGFACO WHERE NUMOS = AD_TCSOSE.NUMOS))) AS OBSOCOR

      ,(SELECT OBS.DESCRICAO
                FROM AD_VGFOBS_2 OBS
                WHERE OBS.NUMOS = AD_TCSOSE.NUMOS) AS PREVIAOBSNFE

      ,(SELECT 0
                FROM DUAL) AS STATUSEST

      ,(SELECT SUM(VLRLIQUIDO)
                FROM AD_TCSREP
                WHERE NUMOS = AD_TCSOSE.NUMOS
                AND ORIGEM = 'D') AS VLREXTRAS

      ,(SELECT SUM(VLRLIQUIDO)
                FROM AD_TCSREP
                WHERE NUMOS = AD_TCSOSE.NUMOS
                AND ORIGEM = 'P') AS VLRPRO

      ,(SELECT SUM(VLRLIQUIDO)
                FROM AD_TCSREP
                WHERE NUMOS = AD_TCSOSE.NUMOS
                AND ORIGEM = 'S') AS VLRSERV

      ,(SELECT SUM(VLRTOTAL)
                FROM AD_TCSREP
                WHERE NUMOS = AD_TCSOSE.NUMOS
                AND ORIGEM IN ('P', 'S', 'D')) AS VLRTOTAL

      ,(SELECT SUM(AD_TCSKM.VLRLIQUIDO)
                FROM AD_TCSREP, AD_TCSKM
                WHERE AD_TCSKM.NUMOS = AD_TCSOSE.NUMOS
                AND AD_TCSKM.NUMOS = AD_TCSREP.NUMOS
                AND ORIGEM = ('D')) AS VLR_KM_GARANTIA

      ,(SELECT SUM(AD_TCSKM.VLRLIQUIDO)
                FROM AD_TCSREP, AD_TCSKM
                WHERE AD_TCSKM.NUMOS = AD_TCSOSE.NUMOS
                AND AD_TCSKM.NUMOS = AD_TCSREP.NUMOS
                AND ORIGEM = ('P')) AS VLR_KM_PRODUTO

      ,(SELECT SUM(AD_TCSKM.VLRLIQUIDO)
                FROM AD_TCSREP, AD_TCSKM
                WHERE AD_TCSKM.NUMOS = AD_TCSOSE.NUMOS
                AND AD_TCSKM.NUMOS = AD_TCSREP.NUMOS
                AND ORIGEM = ('S')) AS VLR_KM_SERVICO

      ,(SELECT SUM(AD_TCSPRO.VLRTOTAL)
                FROM AD_TCSPRO, AD_TCSREP REP
                WHERE AD_TCSPRO.NUMOS = AD_TCSOSE.NUMOS
                AND REP.NUMOS = AD_TCSPRO.NUMOS
                AND REP.ORIGEM = ('S')) AS VlrPecaservico

      ,(SELECT SUM(AD_TCSPRO.VLRTOTAL)
                FROM AD_TCSPRO, AD_TCSREP REP
                WHERE AD_TCSPRO.NUMOS = AD_TCSOSE.NUMOS
                AND REP.NUMOS = AD_TCSPRO.NUMOS
                AND REP.ORIGEM = ('D')) -
            (SELECT SUM(AD_TCSPRO.VLRDESC)
                FROM AD_TCSPRO, AD_TCSREP REP
                WHERE AD_TCSPRO.NUMOS = AD_TCSOSE.NUMOS
                AND REP.NUMOS = AD_TCSPRO.NUMOS
                AND REP.ORIGEM = ('D'))AS VlrPecaGarantia

      ,(SELECT SUM(AD_TCSPRO.VLRTOTAL)
                FROM AD_TCSPRO, AD_TCSREP REP
                WHERE AD_TCSPRO.NUMOS = AD_TCSOSE.NUMOS
                AND REP.NUMOS = AD_TCSPRO.NUMOS
                AND REP.ORIGEM = ('P')) -
            (SELECT SUM(AD_TCSPRO.VLRDESC)
                FROM AD_TCSPRO, AD_TCSREP REP
                WHERE AD_TCSPRO.NUMOS = AD_TCSOSE.NUMOS
                AND REP.NUMOS = AD_TCSPRO.NUMOS
                AND REP.ORIGEM = ('P'))AS VlrPecaProduto

      ,(SELECT SUM(AD_TCSPRO.VLRTOTAL)
                FROM AD_TCSPRO
                WHERE AD_TCSPRO.NUMOS = AD_TCSOSE.NUMOS) -
            (SELECT SUM(AD_TCSPRO.VLRDESC)
                FROM AD_TCSPRO
                WHERE AD_TCSPRO.NUMOS = AD_TCSOSE.NUMOS) AS VlrPecaTotal

      ,(SELECT SUM(AD_TCSSER.VLRTOTAL)
                FROM AD_TCSSER, AD_TCSREP REP
                WHERE AD_TCSSER.NUMOS = REP.NUMOS
                AND AD_TCSSER.NUMOS = AD_TCSOSE.NUMOS
                AND REP.ORIGEM = ('D') ) AS ValorSerGarantia

      ,(SELECT SUM(AD_TCSSER.VLRTOTAL)
                FROM AD_TCSSER, AD_TCSREP REP
                WHERE AD_TCSSER.NUMOS = REP.NUMOS
                AND AD_TCSSER.NUMOS = AD_TCSOSE.NUMOS
                AND REP.ORIGEM = ('S') ) AS ValorSer


      ,(SELECT SUM(AD_TCSSER.VLRTOTAL)
                FROM AD_TCSSER, AD_TCSREP REP
                WHERE AD_TCSSER.NUMOS = REP.NUMOS
                AND AD_TCSSER.NUMOS = AD_TCSOSE.NUMOS
                AND REP.ORIGEM = ('P') ) AS ValorSerProduto


      ,(SELECT SUM(AD_TCSSER.VLRTOTAL)
                FROM AD_TCSSER, AD_TCSREP REP
                WHERE AD_TCSSER.NUMOS = REP.NUMOS
                AND AD_TCSSER.NUMOS = AD_TCSOSE.NUMOS) -
         (SELECT SUM(AD_TCSSER.VLRDESC)
                FROM AD_TCSSER, AD_TCSREP REP
                WHERE AD_TCSSER.NUMOS = REP.NUMOS
                AND AD_TCSSER.NUMOS = AD_TCSOSE.NUMOS) AS ValorSerFinal

     ,(select sum(ad_tcsser.VLRLIQUIDO)
            from AD_TCSSER, ad_tcsrep rep
            where ad_tcsser.NUMOS = rep.NUMOS
        and ad_tcsser.NUMOS = AD_TCSOSE.NUMOS
        AND REP.ORIGEM = 'S'
            ) as valor_liquido_SER

      , (select sum(ad_tcsser.VLRLIQUIDO)
            from AD_TCSSER, ad_tcsrep rep
            where ad_tcsser.NUMOS = rep.NUMOS
        and ad_tcsser.NUMOS = AD_TCSOSE.NUMOS
        AND REP.ORIGEM = 'D'
            ) as valor_liquido_GAR

      , (select sum(ad_tcsser.VLRLIQUIDO)
            from AD_TCSSER, ad_tcsrep rep
            where ad_tcsser.NUMOS = rep.NUMOS
        and ad_tcsser.NUMOS = AD_TCSOSE.NUMOS
        AND REP.ORIGEM = 'P'
            ) as valor_liquido_SER


      , (select sum (ad_tcsser.VLRDESC)
          FROM AD_TCSSER, AD_TCSREP REP
          WHERE AD_TCSSER.NUMOS = REP.NUMOS
          AND AD_TCSSER.NUMOS = AD_TCSOSE.NUMOS
          AND REP.ORIGEM = 'S') as DescServico

        , (select sum (ad_tcsser.VLRDESC)
          FROM AD_TCSSER, AD_TCSREP REP
          WHERE AD_TCSSER.NUMOS = REP.NUMOS
          AND AD_TCSSER.NUMOS = AD_TCSOSE.NUMOS
          AND REP.ORIGEM = 'D') as DescServicoGrar

           , (select sum (ad_tcsser.VLRDESC)
          FROM AD_TCSSER, AD_TCSREP REP
          WHERE AD_TCSSER.NUMOS = REP.NUMOS
          AND AD_TCSSER.NUMOS = AD_TCSOSE.NUMOS
          AND REP.ORIGEM = 'P') as DescServicoProd

      ,AD_TCSPMP.DESCRICAO AS l0_DESCRICAO
      ,AD_TIPATD.DESCRICAO AS l1_DESCRICAO
      ,AD_VGFCUS.DESCRCENCUS AS l2_DESCRCENCUS
      ,AD_VGFMAQ.NROCHASSI AS l3_NROCHASSI
      ,Contato.NOMECONTATO AS l4_NOMECONTATO
      ,Empresa.NOMEFANTASIA AS l5_NOMEFANTASIA
      ,OcorrenciaOS.DESCROCOROS AS l6_DESCROCOROS
      ,Parceiro.NOMEPARC AS l7_NOMEPARC
      ,Parceiro_AD001.NOMEPARC AS l8_NOMEPARC
      ,Produto.DESCRPROD AS l9_DESCRPROD
      ,TipoNegociacao.DESCRTIPVENDA AS l10_DESCRTIPVENDA
      ,TipoNegociacao_AD001.DESCRTIPVENDA AS l11_DESCRTIPVENDA
      ,Usuario.NOMEUSU AS l12_NOMEUSU
      ,Usuario_AD001.NOMEUSU AS l13_NOMEUSU
      ,Usuario_AD002.NOMEUSU AS l14_NOMEUSU
      ,Usuario_AD004.NOMEUSU AS l15_NOMEUSU
                                FROM AD_TCSOSE LEFT JOIN (SELECT DESCRICAO,NUPMP FROM AD_TCSPMP)

         AD_TCSPMP              ON (AD_TCSOSE.NUPMP = AD_TCSPMP.NUPMP)
                                LEFT JOIN (SELECT NUTIPATD,DESCRICAO FROM AD_TIPATD)

         AD_TIPATD              ON(AD_TCSOSE.NUTIPATD = AD_TIPATD.NUTIPATD)
                                LEFT JOIN (SELECT DESCRCENCUS,CODCENCUS FROM AD_VGFCUS)

         AD_VGFCUS              ON(AD_TCSOSE.CODCENCUS = AD_VGFCUS.CODCENCUS)
                                LEFT JOIN (SELECT NUPARMAQ,NROCHASSI,CODPARC FROM AD_VGFMAQ)

         AD_VGFMAQ              ON(AD_TCSOSE.NUPARMAQ = AD_VGFMAQ.NUPARMAQ AND AD_TCSOSE.CODPARCMAQ = AD_VGFMAQ.CODPARC)
                                LEFT JOIN (SELECT NOMECONTATO,CODPARC,CODCONTATO FROM TGFCTT)

         Contato                ON(AD_TCSOSE.CODPARC = Contato.CODPARC AND AD_TCSOSE.CODCONTATO = Contato.CODCONTATO)
                                LEFT JOIN (SELECT NOMEFANTASIA,CODEMP FROM TSIEMP)

         Empresa                ON(AD_TCSOSE.CODEMP = Empresa.CODEMP)
                                LEFT JOIN (SELECT DESCROCOROS,CODOCOROS FROM TCSOOS)

         OcorrenciaOS           ON(AD_TCSOSE.CODOCOROS = OcorrenciaOS.CODOCOROS)
                                LEFT JOIN (SELECT NOMEPARC,CODPARC FROM TGFPAR)

         Parceiro               ON(AD_TCSOSE.CODPARC = Parceiro.CODPARC)
                                LEFT JOIN (SELECT NOMEPARC,CODPARC FROM TGFPAR)

         Parceiro_AD001         ON(AD_TCSOSE.CODPARCMAQ = Parceiro_AD001.CODPARC)
                                LEFT JOIN (SELECT DESCRPROD,CODPROD FROM TGFPRO)

         Produto                ON(AD_TCSOSE.CODPROD = Produto.CODPROD)
                                LEFT JOIN (SELECT X.DESCRTIPVENDA,X.CODTIPVENDA,X.DHALTER
                                FROM TGFTPV X WHERE X.DHALTER = (SELECT MAX(Y.DHALTER)
                                FROM TGFTPV Y WHERE Y.CODTIPVENDA = X.CODTIPVENDA))

         TipoNegociacao         ON(AD_TCSOSE.CODTIPVENDAPRO = TipoNegociacao.CODTIPVENDA)
                                LEFT JOIN (SELECT X.DESCRTIPVENDA,X.CODTIPVENDA,X.DHALTER
                                FROM TGFTPV X WHERE X.DHALTER = (SELECT MAX(Y.DHALTER)
                                FROM TGFTPV Y WHERE Y.CODTIPVENDA = X.CODTIPVENDA))

         TipoNegociacao_AD001   ON(AD_TCSOSE.CODTIPVENDASERV = TipoNegociacao_AD001.CODTIPVENDA)
                                LEFT JOIN (SELECT CODUSU,NOMEUSU FROM TSIUSU)

         Usuario                ON(AD_TCSOSE.CODUSUFECH = Usuario.CODUSU)
                                LEFT JOIN (SELECT CODUSU,NOMEUSU FROM TSIUSU)

         Usuario_AD001          ON (AD_TCSOSE.CODUSUALTER = Usuario_AD001.CODUSU)
                                LEFT JOIN (SELECT CODUSU,NOMEUSU FROM TSIUSU)

         Usuario_AD002          ON(AD_TCSOSE.CODUSUINC = Usuario_AD002.CODUSU)
                                LEFT JOIN (SELECT CODUSU,NOMEUSU FROM TSIUSU)

         Usuario_AD004          ON(AD_TCSOSE.CODUSUMEC = Usuario_AD004.CODUSU)
                                WHERE (((((AD_TCSOSE.CODEMP IN (SELECT  NVL(AD_CODEMP,AD_TCSOSE.CODEMP)
                                FROM TSIUSU WHERE CODUSU = stp_get_codusulogado))))
       				            AND ((AD_TCSOSE.DHCHAMADA BETWEEN :P_PERIODO.INI AND :P_PERIODO.FIN OR :P_PERIODO.INI IS NULL AND :P_PERIODO.FIN IS NULL)
                                AND (AD_TCSOSE.DTFECHAMENTO BETWEEN :P_PERIODOF.INI AND :P_PERIODOF.FIN OR :P_PERIODOF.INI IS NULL AND :P_PERIODOF.FIN IS NULL)
                                AND AD_TCSOSE.CODEMP = :P_CODEMP OR :P_CODEMP IS NULL
       				            AND AD_TCSOSE.STATUSOS = :P_STATUSOS OR :P_STATUSOS IS NULL)))
