SELECT
ITE.CODPROD,
PRO.DESCRPROD,
ITE.USOPROD,
(CASE
    WHEN VOA.CODPROD IS NULL THEN ITE.QTDNEG
	WHEN VOA.DIVIDEMULTIPLICA = 'D' THEN ITE.QTDNEG * VOA.QUANTIDADE
	ELSE ITE.QTDNEG / VOA.QUANTIDADE
END) AS QTDNEG,
(CASE
    WHEN VOA.CODPROD IS NULL THEN ITE.VLRUNIT
	WHEN VOA.DIVIDEMULTIPLICA = 'D' THEN ITE.VLRUNIT / VOA.QUANTIDADE
	ELSE ITE.VLRUNIT * VOA.QUANTIDADE
END) AS VLRUNIT,
ITE.CODVOL,
ITE.VLRDESC,
ITE.QTDNEG * ITE.VLRUNIT AS TOTALITEM,
ITE.VLRTOT - ITE.VLRDESC AS TOTLIQ,
ITE.CODLOCALORIG AS LOCALIZACAO,
PRO.AD_PARTNUMBER
FROM TGFITE ITE
INNER JOIN TGFPRO PRO ON(ITE.CODPROD = PRO.CODPROD)
LEFT JOIN TGFVOA VOA ON(
    VOA.CODPROD = ITE.CODPROD AND
	VOA.CODVOL = ITE.CODVOL AND
	(((ITE.CONTROLE IS NULL OR PRO.TIPCONTEST NOT IN ('I', 'S', 'P')) AND VOA.CONTROLE = ' ') OR (ITE.CONTROLE IS NOT NULL AND ITE.CONTROLE = VOA.CONTROLE))
)
WHERE
ITE.NUNOTA = $P{NUNOTA} AND
ITE.SEQUENCIA > 0
ORDER BY ITE.CODPROD