SELECT
       NCM,
       AD_PARTNUMBER,
       CTE.DTCONTAGEM, CTE.CODPROD,
       (SELECT DESCRPROD FROM TGFPRO WHERE CODPROD = CTE.CODPROD) AS PRODUTO, CTE.CODVOL,
       CTE.CODLOCAL || '-' ||
       (SELECT L.DESCRLOCAL FROM TGFLOC L WHERE L.CODLOCAL = CTE.CODLOCAL) AS LOCAL,
       CTE.QTDEST,  CASE WHEN CTE.TIPO = 'P' THEN 'PRÓPRIO' ELSE 'TERCEIROS' END AS TIPO,


NVL((SELECT NVL(MAX(CUSSEMICM),0)
     FROM TGFCUS
     WHERE CODPROD = CTE.CODPROD
     AND CODEMP = CTE.CODEMP
     AND DTATUAL = (SELECT MAX(DTATUAL)
                       FROM TGFCUS CN
                       WHERE CODPROD = CTE.CODPROD
                         AND DTATUAL <= CTE.DTCONTAGEM
                         AND CODEMP = CTE.CODEMP
                     )
      ) * CTE.QTDEST,0 ) AS CUS_SEMICMS,
CTE.CODEMP

,(SELECT NVL(MAX(CUSSEMICM),0)
     FROM TGFCUS
     WHERE CODPROD = CTE.CODPROD
     AND CODEMP = CTE.CODEMP
     AND DTATUAL = (SELECT MAX(DTATUAL)
                       FROM TGFCUS CN
                       WHERE CODPROD = CTE.CODPROD
                         AND DTATUAL <= CTE.DTCONTAGEM
                         AND CODEMP = CTE.CODEMP
                     )
      ) AS CUS_ITEM_SEMICMS

FROM TGFCTE CTE
INNER JOIN TGFPRO PRO ON (CTE.CODPROD = PRO.CODPROD AND (PRO.CODGRUPOPROD >= 30101000 AND PRO.CODGRUPOPROD <= 31601000))
WHERE CTE.DTCONTAGEM = TO_DATE('24/12/2020','DD/MM/YYYY')
AND CTE.CODEMP = 6
AND CTE.QTDEST > 0